version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - db
    networks:
      - mon_reseau

  db:
    image: mariadb:10.6
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rgl
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    networks:
      mon_reseau:
        aliases:
          - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - mon_reseau

volumes:
  db_data:

networks:
  mon_reseau:
    driver: bridge
